/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.iftm.mavenproject1;

/**
 *
 * @author IFTM
 */
public class NewJFrame extends javax.swing.JFrame {

    Conversor conversor = new Conversor();

    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        RBCelcius1 = new javax.swing.JRadioButton();
        RBFahrenheit1 = new javax.swing.JRadioButton();
        RBKelvin1 = new javax.swing.JRadioButton();
        RBCelcius2 = new javax.swing.JRadioButton();
        RBFahrenheit2 = new javax.swing.JRadioButton();
        RBKelvin2 = new javax.swing.JRadioButton();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bT1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup2.add(RBCelcius1);
        RBCelcius1.setText("Celsius");
        RBCelcius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBCelcius1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(RBFahrenheit1);
        RBFahrenheit1.setText("Fahrenheit");

        buttonGroup2.add(RBKelvin1);
        RBKelvin1.setText("Kelvin");
        RBKelvin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBKelvin1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBCelcius2);
        RBCelcius2.setText("Celsius");

        buttonGroup1.add(RBFahrenheit2);
        RBFahrenheit2.setText("Fahrenheit");

        buttonGroup1.add(RBKelvin2);
        RBKelvin2.setText("Kelvin");

        TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Conversão de Temperatura");

        bT1.setText("Converter");
        bT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RBCelcius1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RBFahrenheit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RBKelvin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bT1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RBKelvin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RBFahrenheit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RBCelcius2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBCelcius2)
                    .addComponent(RBCelcius1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBFahrenheit2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bT1)
                                .addGap(3, 3, 3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBKelvin2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RBFahrenheit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBKelvin1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBKelvin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBKelvin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBKelvin1ActionPerformed

    private void RBCelcius1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBCelcius1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBCelcius1ActionPerformed

    private void TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF2ActionPerformed

    private void bT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT1ActionPerformed
        if (RBCelcius1.isSelected() && RBKelvin2.isSelected()) {
            int a = Integer.parseInt(TF1.getText().trim());

            TF2.setText(String.valueOf(conversor.calculaCK(a)));
        } else if (RBCelcius1.isSelected() && RBFahrenheit2.isSelected()) {
            int a = Integer.parseInt(TF1.getText().trim());

            TF2.setText(String.valueOf(conversor.calculaCF(a)));
        } else if (RBKelvin1.isSelected() && RBCelcius2.isSelected()) {
            int a = Integer.parseInt(TF1.getText().trim());

            TF2.setText(String.valueOf(conversor.calculaKC(a)));
        } else if (RBKelvin1.isSelected() && RBFahrenheit2.isSelected()) {
            int a = Integer.parseInt(TF1.getText().trim());

            TF2.setText(String.valueOf(conversor.calculaKF(a)));
        } else if (RBFahrenheit1.isSelected() && RBCelcius2.isSelected()) {
            int a = Integer.parseInt(TF1.getText().trim());

            TF2.setText(String.valueOf(conversor.calculaFC(a)));
        } else if (RBFahrenheit1.isSelected() && RBKelvin2.isSelected()) {
            int a = Integer.parseInt(TF1.getText().trim());

            TF2.setText(String.valueOf(conversor.calculaFK(a)));
        } else {
            TF2.setText(TF1.getText());
        }
    }//GEN-LAST:event_bT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBCelcius1;
    private javax.swing.JRadioButton RBCelcius2;
    private javax.swing.JRadioButton RBFahrenheit1;
    private javax.swing.JRadioButton RBFahrenheit2;
    private javax.swing.JRadioButton RBKelvin1;
    private javax.swing.JRadioButton RBKelvin2;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JButton bT1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
